### ISSUE TITLE
bar dissapper as I hover mouse over it

### ISSUE THREAD

**Issue by iamrajee** [khanhas/Polybar#10]
![1](https://user-images.githubusercontent.com/25712145/69139586-d3c6d300-0ae6-11ea-87c9-8dfcd83aac7f.png)
![2](https://user-images.githubusercontent.com/25712145/69139597-d7f2f080-0ae6-11ea-9b42-3101c3c8487f.png)
See image for reference.
In polybar setting, I enable something named mouseCoverOn(not sure about its name?) from then bar disappears as I move the mouse over it. Now I'm unable to disable it as I can't access setting from where I had enabled it. Also, I tried reinstalling it but the same happens with it as well.

**Comment by khanhas** [comment]
Open Rainmeter Manager in system tray, load the setting skin and revert what you did.

**Comment by iamrajee** [comment]
That worked. Thankyou.
