### ISSUE TITLE
Cant set proper width

### ISSUE THREAD

**Issue by alik15** [khanhas/Polybar#24]
When i installed the bar it was too big(my monitor is 1366 and the bar was 1866 long) when i changes the length it just shortened the black background/color of the bar and not the bar itself 
![Screenshot 2021-04-20 011317](https://user-images.githubusercontent.com/74252694/115298426-e67b8680-a176-11eb-97bd-9e6eccb69cb5.png)

**Comment by khanhas** [comment]
Switch to modules page and change their positions

**Comment by alik15** [comment]
Ohhh it works, I feel dumb now. Thanks mate!!!
