### ISSUE TITLE
Cant get the Taskbar to work.

### ISSUE THREAD

**Issue by MMA92** [khanhas/Polybar#3]
Everything else seems to work fine. But the taskbar module never shows up.

**Comment by Strazdonis** [comment]
Do you get any errors in the logs? Maybe the placement is just off?

**Comment by MMA92** [comment]
placement seems fine. but i got this error in the log

Plugin: Unable to load "Mouse" (error 126) (Polybar\Polybar.ini - [TaskbarMousePlugin])
Plugin: Unable to load "ProgramOptions" (error 126) (Polybar\Polybar.ini - [ProgramOptions])
Calc: Division by 0 (Polybar\Polybar.ini - [MovingCondition])

**Comment by khanhas** [comment]
Please try reinstall Polybar from rmskin, remember to check/tick Mouse and ProgramOptions plugins when installing

**Comment by MMA92** [comment]
I Unzipped the archive to the Rainmeter Skins folder and Refreshed Rainmeter. Then I loaded Polybar.ini . Taskbar Module is loaded and placed correctly. Still not visible. Am I doing something the wrong way?

**Comment by khanhas** [comment]
Please install from rmskin package from https://drive.google.com/file/d/0B9O42meWKBatck1Yb1gxYlp6ekU/view?usp=sharing

**Comment by khanhas** [comment]
Then you can extract this repository to Polybar folder to update some new features

**Comment by MMA92** [comment]
That fixed it for me thank you very much :)
