### ISSUE TITLE
Neoristic Desktop Indicator White

### ISSUE THREAD

**Issue by davebattles** [khanhas/Polybar#4]
Neoristic Desktop Indicator White

I haven't been able to figure out how to get it to properly colorize with the theme. If I clone the repo fresh, the issue still persists for me.

[example of issue](https://streamable.com/u7z91)

**Comment by khanhas** [comment]
Use Edit Module setting to open WorkspaceManager module inc file.
Add 
```
BackgroundTrait = StrokeWidth 0 | Fill Color #Color_Scheme1#
```
in ![[WorkspaceCurrent] section](https://github.com/khanhas/Polybar/blob/master/Themes/Neoristic/WorkspaceManager.inc#L70)
Save and refresh Polybar.

**Comment by davebattles** [comment]
There you go, perfect. Thank you
