### ISSUE TITLE
VirusTotal results for v1.0 

### ISSUE THREAD

**Issue by kapitanluffy** [khanhas/Polybar#7]
Here's the VirusTotal result for the 1.0 release.

https://www.virustotal.com/#/file/2f1580d826a08ae02b62e3ed2a60b5deb1ee584bdb231c7e63c9c54b57614277/detection

The autoscripts have their source code provided. You can recompile them if you don't trust the provided exe files.

NirCMD is NirCMD. Download it on nirsoft if you don't trust it too.

RainRGB is malicious. I think you can download it on the official RM forum.
https://www.virustotal.com/#/file/e4814bac41a57772534536f484bf0d527a555a3c22b53f70c92e35ca664f1cfb/detection

Taskbar Magic is malicious too. Though the source code is provided as well.
https://www.virustotal.com/#/file/d0e223e738cb59ead407ffffcb8aa6dfafcf1297981944844132c16358501195/detection

**Comment by khanhas** [comment]
AHK and AutoIT have long history of false-positive virus detection with various of "anti-virus engine" or whatever they call themselves. This topic has been discussed too many times, you can find them in their forums. I have been asked about this too many times. Each time I cringed a little harder.  
By the way, if you download new version of NirCMD from its website and scan with virustotal, it has more "virus" than the version I packaged in Polybar. Is it received any real virus report? Can virustotal report be trusted?
Please check the fact before giving a bold statement that I'm spreading malicious software here.

**Comment by Drgabi18** [comment]
RainRGB is made by the head developer of the Rainmeter project, I trust that Jeff is not a bad guy :P

**Comment by kapitanluffy** [comment]
Sorry for the misunderstanding. I am not saying you are spreading malicious software. I am merely putting the virustotal report for v1.0 for others to see.

As I mentioned the AutoIT and AHK scripts has their source code provided.

As for the other exe's, I mentioned that if you don't trust the packaged ones, you can download them instead.

I never mentioned that people should avoid using polybar. In fact, I'm using it right now.
